// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoJCiFZeRRX7ngdR4wYUPpY1rGzJdZ5I4',
    appId: '1:205801101065:web:6f564e451dd046b6d725d8',
    messagingSenderId: '205801101065',
    projectId: 'diary-app-database',
    authDomain: 'diary-app-database.firebaseapp.com',
    storageBucket: 'diary-app-database.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCj8kjdcMlqsNCi4KtmhJ3RwkJLWf0jRPw',
    appId: '1:205801101065:android:b2644aca95f3042cd725d8',
    messagingSenderId: '205801101065',
    projectId: 'diary-app-database',
    storageBucket: 'diary-app-database.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAa0b0PpXnNH2_NcLjElfVKYGLabJGNXPw',
    appId: '1:205801101065:ios:9dca38e956dfab3dd725d8',
    messagingSenderId: '205801101065',
    projectId: 'diary-app-database',
    storageBucket: 'diary-app-database.firebasestorage.app',
    iosBundleId: 'com.example.diaryApp',
  );
}
